apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calculator

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml

commonLabels:
  app: calculator-api
  version: v1

images:
- name: calculator-api
  newTag: latest
