name: Local Deploy Node.js Project

on:
  push:
    branches:
      - main   # Change to your branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker (Optional if already installed)
        uses: docker/setup-buildx-action@v2

      - name: Start project with Docker Compose
        run: |
          cd ./   # Path to your docker-compose.yml
          docker-compose down
          docker-compose up -d
