name: Deploy Node.js Project with Docker Compose

on:
  push:
    branches:
      - main   # Change to your branch if needed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Optional: Set up Docker Buildx (for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Deploy latest code using Docker Compose
      - name: Deploy latest code
        shell: powershell
        run: |
          # Navigate to the folder containing docker-compose.yml
          cd ${{ github.workspace }}

          Write-Host "Stopping old containers..."
          docker-compose down

          Write-Host "Building and starting containers with latest code..."
          docker-compose up -d --build

      # 4. Wait for services to be ready
      - name: Wait for services
        shell: powershell
        run: |
          Write-Host "Waiting for 10 seconds..."
          Start-Sleep -Seconds 10
          Write-Host "Services should be up now."

      # 5. Optional: List running containers to verify
      - name: List running containers
        shell: powershell
        run: docker ps
