name: Self-Hosted Smoke Test

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    steps:
      - name: Print hello
        run: echo "Hello from self-hosted runner!"

      - name: Show runner info
        run: |
          uname -a || ver
          whoami || echo "whoami not available"
          pwd

      - name: Create a test file in workspace
        run: |
          echo "$(date) - smoke test" > SMOKE_TEST_OK.txt
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: SMOKE_TEST_OK.txt


