name: Deploy Node.js Project with Docker Compose

# Trigger the workflow on push to main branch (change branch if needed)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Optional: Set up Docker Buildx (if using advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub (optional, if pulling private images)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Deploy latest code using Docker Compose
      - name: Deploy latest code
        run: |
          cd ./  # path to your docker-compose.yml
          echo "Stopping old containers..."
          docker-compose down
          echo "Building and starting containers with latest code..."
          docker-compose up -d --build

      # 5. Optional: Wait for services to be ready
      - name: Wait for services
        run: |
          timeout /t 10  # Wait 10 seconds (Windows)
          echo "Services should be up now."

      # 6. Optional: Check running containers
      - name: List running containers
        run: docker ps
