name: Local Deploy Node.js Project

on:
  push:
    branches:
      - main   # Change to your branch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker (Optional if already installed)
        uses: docker/setup-buildx-action@v2

      - name: Start project with Docker Compose
        run: |
          cd ./   # Path to your docker-compose.yml
          echo "Git commit: $(git rev-parse --short HEAD)"
          docker-compose version
          echo "Stopping stack..."
          docker-compose down || true
          echo "Rebuilding images without cache..."
          docker-compose build --no-cache --pull
          echo "Starting stack..."
          docker-compose up -d --force-recreate
          echo "Images used by running containers:"
          docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.ID}}\t{{.Status}}'
          echo "Local images for context:"
          docker images

      - name: Show container logs (brief)
        run: |
          docker-compose ps
          docker-compose logs -t --tail=50
